### ISSUE TITLE
Specification: Metrics Explorer navigation

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#131]
Metrics explorer at the moment is just a list of 2000 items with a search bar at the top.

![screen shot 2017-07-20 at 12 33 42 pm](https://user-images.githubusercontent.com/98312/28428541-b5e4cb74-6d47-11e7-810c-f7e26737d094.png)

**Comment by shanberg** [comment]
Can we break the paths out into tags to filter the list?

**Comment by spmcbride1201** [comment]
I'm not really sure what you mean by breaking out into tags, but I've generally found parsing these keys to be somewhat fragile. Once we're scraping prometheus scrape targets, that might force more predictable structure around delimiters and other characters that we can take advantage of.

**Comment by shanberg** [comment]
So we may at some point have a cleaner output that's more easily readable and navigable by a human?

If it does need to be a giant pool of list items at the same level of hierarchy, I'm hoping we can find some other way to organize them. At the _very_ least can we provide an alphabetical grouping and anchor links until we come up with something better?

**Comment by shanberg** [comment]
![Explorer-b](https://user-images.githubusercontent.com/98312/28436084-b73c7dac-6d63-11e7-9858-bb9cf53d8042.png)

**Comment by spmcbride1201** [comment]
So that's dependent on functionality similar to how I was creating a fake JSON object: assuming use of a commonly-accepted delimiter and finding and correcting for edge cases (like in Finagle, where the slash is used for delimiters and also contained inside keys derived from paths). Customers are going to likely be able to add in all sorts of crazy keys that we will never be able to predict. That's why I'm hesitant to try to rely on hierarchical structures we have to guess at.

Just to get things working from `gm-fabric-jvm` I had this monster function will all of these checks and one-off corrections for edge cases. Later, when I started to add Golang support, all the JVM stuff was wrong, so I have to create another monster function called `parseGolangMetrics` with all of it's own craziness.

This is ultimately why I moved to the long crazy list and the search bar. It can accommodate any keys that a customer throws at them, no matter how malformed or insanely delimited. It strips out all sorts of stuff that can break on our end. What about perhaps hiding the list by default and enhancing the search with better typeahead?
