### ISSUE TITLE
Reimplement Docker Compose and Graphite/statsd container to use TCP

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#173]

**Comment by joshua-rutherford** [comment]
Sad as I realize once again why I hate graphite.

**Comment by joshua-rutherford** [comment]
And taking up the mantle of actually building an envoy with some other (any really) metrics sink.

**Comment by joshua-rutherford** [comment]
Then again the docker image for building envoy has a single layer in it that is 781MB.  Yikes.

**Comment by joshua-rutherford** [comment]
Ok, I've take some time to think about this issue and I really don't think Graphite is the right solution either.  In all honestly, using a TSDB backed by Cassandra or HBase is less complex to setup and maintain.  At Opower we were originally were using Graphite and we had one of about 10 full time infrastructure engineers who new what was going on.  We migrated to OpenTSDB but that was because our business was already a Hadoop shop so HBase was already around.

That said, I don't think that our first step here should be to require any solution with this much overhead.  For this reason, I really like Prometheus but this leaves the issue of Envoy not providing what we need and having to jump through some hoops (hops actually) to get what we need.  

If we are truly investing in Envoy, we must be capable of working within it, not just with it.  So I've done some sleuthing and discovered that this is all they are doing to present their metrics via the admin panel. https://github.com/lyft/envoy/blob/master/source/server/http/admin.cc#L265.  This is pretty straight forward and could be handled by a build that patches it to give prometheus format.  

So I may spike this tonight if I have time, but lets just say that the standard build is a bit long running.

**Comment by spmcbride1201** [comment]
Okay. I trust your experience and judgement on this. 

Few thoughts: 

- The process of trying to add first-class Prometheus support to Envoy is probably going to be a pretty drawn out process. I presume the goal is the monkey-patch our fork, build Grey Matter off our fork, and then in parallel try to contribute the changes upstream? It's probably worth figuring out if this is something that Lyft would even consider.
- Does this shift the TSDB out beyond Sep 8, making it more critical for me to build out an alternate demo-able solution?
- Are we comfortable with accepting the Prometheus assumption that time series metrics are useful-yet-not-business-critical? The simplicity of their system seems based around the idea that 90% of the useful metrics are like in the last 24 hours and that loss of data is acceptable. If I was a a SysOps, I suspect that trade-off would make a lot of sense. For what we're going to be building over the next six months, I think the trade-off also makes a lot of sense. I'm just concerned that we might end up steering the product into the realm of using timeseries data to build ML models and try to build "autonomic self-healing robotic brain distributed systems," and the sense of how critical this data becomes might shift us out of the sweet spot for Prometheus. I kid a bit, but it seems like we should make sure we have plans to evolve the architecture based on how the scalability / criticality of the data might evolve. E.g. what if a customer in a regulated industry has a hard requirement for archiving this timeseries data?

**Looking at Prometheus 2.0 stuff, it seems like this might be an evolving space**

**Comment by spmcbride1201** [comment]
I think that this is probably closed, but I'm going to roll it forward to 3.0 and close it in conjunction with successful fetching of metrics from the graphite API.
