### ISSUE TITLE
Add auth throughout App

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#343]
![image](https://user-images.githubusercontent.com/8700322/29533182-b56d37f8-867e-11e7-87e4-96ab336c9b82.png)

**Comment by tilleryd** [comment]
After thinking about this some more I came to the conclusion that we shouldn't add any auth code to the dashboard.  TLS termination is handled by Nginx.  If the user successfully authenticates with Nginx that's sufficient for the entire dashboard to render.  If they don't , Nginx should serve up nice 401 error page.  This will maintain a separation of concerns and allow the dashboard to remain as an open source repository because we won't be including any authentication logic that's specific to government use cases.

**Comment by chrismholmes** [comment]
PKI authentication is fine for the tactical environments we spoke about.  Please do not change this or add further requirements.  Authorization throughout the application will be necessary but needs to be designed and clear tickets need to be associated.  This is backlogged and will most likely be introduced when we introduce authentication and authorization via oAuth.

**Comment by spmcbride1201** [comment]
Closing this, as I view this as completed for this scope of work. Access to the dashboard is currently controlled by the edge environment's PKI authentication. The `discovery-service` has the ability to limit user access to microservices via the `authorized` key returned by the `/services` route. Soft authentication is currently implemented into the client-side router based on this key.
