### ISSUE TITLE
Screen Reader UX for graph components

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#47]
The charts are currently incomprehensible to screen readers. It seems like the best UX for visually fully impaired folks would be presenting the data powering the chart as a table. However, some sort of a description of the statistics (mean, peak, trough) might be better still.

**Comment by spmcbride1201** [comment]
Conversation with visually impaired friend: 
![image](https://cloud.githubusercontent.com/assets/8700322/24880342/0da7c30a-1e08-11e7-8603-8d4b749771f4.png)

**Comment by spmcbride1201** [comment]
@7ruth - I'm curious about your thoughts around this issue. It seems like the approach that my buddy Aser suggested is a reasonable baseline. I had also discussed with @kaitmore the idea of prototyping some sort of data sonification via the new Web Audio API. https://en.wikipedia.org/wiki/Sonification

**Comment by 7ruth** [comment]
The discussion you had above definitely sounds like a reasonable baseline. I would emphasize that metrics around the data might be the most important pieces since most of the time you really care about time period low, high, median and average and then some sense of where the data is trending. Regarding sonification/ audification... that can help visually impaired people understand those metrics but my main concern would be about speed of playback and controls around the playback (can they slow it down or speed it up or keep replaying it for example) (also due to me never seeing this being used to display time series data and I am sure user not being used to that type of interface it might cause confusion, for example what if the user has trouble telling apart values of the pitch (higher vs lower)).

**Comment by spmcbride1201** [comment]
Yeah, good points. I view the sonification thing as more of an experimental / Fracking Friday thing that brings up all sorts of UX questions, as you point out. I'm going to break this out into an epic and add individual issues into this.
