### ISSUE TITLE
Dashboard graphs showing negative values after services restart

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-dashboard#501]
If a service has been restarted after being hit _n_ number of times, the graph of requests per second will show negative values.

**Comment by joshua-rutherford** [comment]
Just capturing some of the research on this here.  The individual services and the discovery service all seem to behave as expected (i.e., the service registers as a completely different instance in zookeeper and the discovery service stops returning metrics for the old instance).  The only change on that end is that the discovery service is returning a 200 without any metrics instead of a 404.  This will be tracked under: https://github.com/DecipherNow/discovery-service/issues/32

**Comment by spmcbride1201** [comment]
I'm going to stop all front-end efforts to filter this out, as this behavior would point to something anomalous on the backend, and it would be really helpful to better understand the conditions when this happens.

**Comment by joshua-rutherford** [comment]
The fix for the erroneous status codes from the backend is deployed.
