### ISSUE TITLE
Service Instance: gracefully handle downed instances

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#620]
2 scenarios:
1. A user has bookmarked a service instance URL.  The instance goes down.  The user clicks on the bookmark and the service instance page loads.  The data is zeroed out and the error message says "Fetching metrics failed".

2. A user is currently on an instance page and the instance goes down.  On the next poll the "Fetching metrics failed" error message will display.

In both cases we need to display message that says the instance has gone down.  We should keep the user on the page and NOT redirect.  It's good for the user to consciously leave the page instead of the app arbitrarily redirecting them because we don't know if they'll be looking at the page when this happens.

**Comment by spmcbride1201** [comment]
It seems like we'd check this just like we currently check authentication, but with authentication we immediately clear metrics and force redirect to the fabric dashboard.

I guess I'm not sure if I agree about not redirecting. We should discuss further because I think allowing a user to stay on an instance dashboard for a downed instance brings up a bunch of other UX questions and additional requirements in the Settings Pane.
