### ISSUE TITLE
Highlighting of breadcrumbs is cut off

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#759]
Cut off on top, left, and bottom in Chrome and Safari
Cut off on left in Firefox ESR
???? in IE11 or Edge

![image](https://user-images.githubusercontent.com/8700322/32191005-f92db844-bd85-11e7-9c50-5c53b21a87f3.png)

**Comment by shanberg** [comment]
Interesting issue. We've hidden the top-level breadcrumb in cases where it matches the Brand text, in order to reduce the redundancy of identical consecutive linked text items. Perhaps instead we should actually use `display: none;`, because if it's redundant, we truly do mean to remove it from the content.

**Comment by shanberg** [comment]
Waiting to address this until the new app header is merged.

**Comment by spmcbride1201** [comment]
Blocked by #662

**Comment by shanberg** [comment]
This appears to be OBE.
