### ISSUE TITLE
No easy way to navigate to previous page after opening settings page

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#760]
When a user clicks the settings cog from a dashboard, there should be some sort of way for them to go to the last viewed dashboard when they are done tweaking settings.

**Comment by shanberg** [comment]
We have that problem generally, because the information architecture of this app is so broad that it's difficult to generalize the navigation components in a usable and attractive way. The first solution that comes to mind is a general back/up button, to send the user up one level of navigational hierarchy.

We had this on the previous iteration of the main nav, but haven't solved the problem yet with the new breadcrumbs+title+tabs layout.

![screen shot 2017-10-30 at 3 42 49 pm](https://user-images.githubusercontent.com/98312/32191921-08515c10-bd89-11e7-8f5c-2550ed79a1f8.png)

**Comment by spmcbride1201** [comment]
This wouldn't solve the issue as the navigational buttons follow our app routing, and the Fabric dashboard is always the direct ancestor of the settings panel. In pretty much every other use case other than the settings panel, I think the breadcrumbs are sufficient. This makes me think that we should table this issue until after our initial release so we have more time to think this through.

**Comment by shanberg** [comment]
I think navigating up from the Settings page to the Fabric page is appropriate, and we've planned a Configuration page for Service and Instance controls. In a case where you want to go to the previous page from an unrelated page, that's what the browser Back button is for. Though I concede if we've confused the navigation so much that users _do_ feel lost if they go to Settings, it's clearly not enough.

I agree, we should spend at least a few days with the new navigation, and use that time to figure out what we expect from the navigation.
