### ISSUE TITLE
Sidebar and breadcrumb links to services go to the dashboard

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#805]
When viewing a specific instance of a service, the link at the top the sidebar with the service name and the breadcrumb with the service name (immediately to the right of the "fabric" breadcrumb) both navigate back to the dashboard page rather than to the expected service page (the one containing the list of instances).

**Comment by spmcbride1201** [comment]
Validated that this router is misbehaving.

**Comment by karinakeen** [comment]
@spmcbride1201  Clicking on the service name on the breadcrumb will take you back to the main fabric page because router doesn't know the service version number and won't find an instance by service name only.  (In case same service having multiple versions)  Clicking on the version immediately next to the service name will take you to the instance view of the specific service version.  Do you want the router to find the matching service name without version and direct the user back to that service? Then we have to assume all service names are unique.

**Comment by kaitmore** [comment]
@karinakeen  Right now, the only way to find the service without the version would be to loop through all the services and match on the beginning of the key.

**Comment by karinakeen** [comment]
@kaitmore Right, and I think each service name/version has their own of instances, so I think maybe instead of separating service name and version on breadcrumb, it should be one link  `Fabric > Service > 1.0 > ...` -> `Fabric > Service 1.0 > ...` on breadcrumb

**Comment by kaitmore** [comment]
@karinakeen Gotcha, yeah, that makes sense to me!
