### ISSUE TITLE
Explorer Chart Responsiveness Issue

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#876]
When the Explorer scene renders with a small screen width and is then expanded, the GMLineChart does not responsively expand. Because the GMLineChart does responsively grow in other scenes like JVM, this seems to have to do with the wrapping DIV.

Behavior recorded and available for replay at https://www.youtube.com/watch?v=H8cTNpBGZz0&feature=youtu.be

**Comment by 7ruth** [comment]
@spmcbride1201 Could you please re-test on latest master when you see this? 

I can't replicate anymore and looking at the size of the chart in the video I think you tested before my PR was merged in earlier today. It seems that the issue has been fixed. Please let me know if thats not the case.

**Comment by spmcbride1201** [comment]
On master, it seems to be horizontally responsive now, but there's some odd vertical overflow behavior that appears at narrow widths and the chart doesn't seem to be vertically responsive. It looks like the height of the chart is hard-coded to 320px.

**Comment by 7ruth** [comment]
I implemented a check for window width when the chart component gets mounted. I noticed that 320px works for all desktop browser zooms but not for mobile, so if the page is loaded on mobile (narrow width) that setting becomes 200px, which works well for all mobile formats. 

It doesn't resize as you move the browser size because I didn't think there would be a scenario when a user would switch between desktop sized window to a mobile sized window without a reload of the page or navigation to other tabs. I can show you what I mean later today if my description is not clear/ or if you think that above scenario is likely to happen I find another way. The limitation here is that I can't pass none digit width to dychart options such as 90vw or something em based.
